### PR TITLE
Add git features to dancer2 gen command

### PR DESCRIPTION
**Pull request by cromedome**
Full disclosure: this is total fluff. That being said, I was thinking of users (new users, specifically), and things that might help them out. So I added a couple of items to the `dancer2 gen` command:

* `-g / --git` - Init a git repo in the new project directory, and commit the skel automatically.
* `-r / --remote` - set the git remote to push to.

### CODE REVIEW

**Comment by racke** [comment]
I would suggest to add proper .gitignore files as well.

**Comment by cromedome** [comment]
I'll add one later today.

**Comment by cromedome** [comment]
Done. It's thin but maybe enough?

**Comment by cromedome** [comment]
This is a mess. Closing the PR, deleting the branch, pulling the relevant commits into a cleaner branch.

**Pull request closed without merging**
