### PR TITLE
use Ref::Util in Core

### PR DESCRIPTION
**Pull request by mickeyn**
any reason not to use Ref::Util in all ref checks in Core?

### CODE REVIEW

**Comment by cromedome** [comment]
None that I can see. :+1: I like this - looks a lot cleaner to me.

**Comment by xsawyerx** [comment]
`Ref::Util` is only XS at the moment. I need to rerelease the PP implementation of it and have `Ref::Util::XS` be the XS version. Then `Ref::Util` will try to load the XS version automatically.

This PR would stay the same, though. :)

**Comment by mickeyn** [comment]
OK, so on-hold until that is done.

**Comment by SysPete** [comment]
@xsawyerx any reason not to merge this one now? I guess we'd need an appropriate prereq for Ref::Util::PP.

**Comment by xsawyerx** [comment]
Nope. We can merge it. The requirement could say `Ref::Util` since that will try to also install `Ref::Util::XS` if you support XS.

**Comment by SysPete** [comment]
:+1: also removed 'on hold' from title.

**Comment by mickeyn** [comment]
fixed conflicts

**Comment by cromedome** [comment]
Thank you!

**Pull request merged**
