### PR TITLE
configuration bugfix + enhancement

### PR DESCRIPTION
**Pull request by perlpilot**
I've tried to keep the commits atomic so that they can be applied or not individually.  The first three commits are essentially for #1149.  To wit: 

* Once we find a config file in each of the main dir and in environments, don't use any others. (i.e. don't use both `config.ini` *and* `config.json` simultaneously if both files happen to be there.)
* Generate warnings if the user happens to have multiple config files in the main dir (e.g. both `config.json` and `config.yaml`) because in that situation, how is the user to know which was used?
* Let the user specify via an environment variable the configuration extension and only look for files with that extension.  However, there is no checking that this extension is a valid type that Config::Any understands.
* what started me looking at the config generation in the first place: at $work we have some developer configuration information that is common across all developers, but we also have some config info that's specific to each developer.  This commit allows for files such as `environments/my-development.yaml` for such cases.

### CODE REVIEW

**Comment by perlpilot** [comment]
Any love for this PR?

**Comment by cromedome** [comment]
My bad. Started working with it, haven't had the time to finish. Sorry!

**Comment by mrmaloof** [comment]
I love it. We could also really use developer specific configuration.

**Comment by veryrusty** [comment]
As this PR is proposed, it will break existing deploys by limiting the configuration load to the first found extension.

There are some good ideas here that should be taken further:
  * Being more explicit about what config files are loaded. eg. logging each file as its read/merged.
  * Using an env var to limit the extensions, like `$ENV{DANCER_CONFIGFILE_EXT}`, and
  * A prefix/suffix for local overrides. My preference is `_local` as a suffix (see #47 too).
 
The `$ENV{DANCER_ALT_CONFIG}` is seems somewhat conflated. You could also point it at a file that Config::Any can't handle.  Another (hopefully simpler) approach is to have the prefix/suffix option on both the `config` and the `environment` file.

Once the above is in place, then there is scope look at only loading configuration from the first found extension, and deprecate existing functionality as necessary.

**Comment by SysPete** [comment]
Rather than prefix/suffix for local overrides I'd much prefer to see a `config.d` directory as suggested in #47. This could even be implemented via a config key in config.yml (or whatever) such as:
```
config_dir: config.d
```
and also allow a list:
```
config_dir:
    - config.d
    - local.d
```
Otherwise agree 100% with @veryrusty and I don't want to see changes that would break existing projects.

**Comment by racke** [comment]
Yes, I second @SysPete. Directory works better.

**Comment by perlpilot** [comment]
@veryrusty Yes, this will break existing deployments that rely on this "feature" of how config files are loaded.  How many do you think that is?   I'm all for backwards compatibility, but not for a "feature" that seems more accidental that purposeful.

Below, I've quoted the stuff I blathered on IRC the other day for anyone who would care to comment.

> \<perlpilot> veryrusty: why exactly?  what's the use-case for having both config.yml and config.json?
\<perlpilot> veryrusty: also, you realize that D2 will currently load config.json first, then config.yml and any settings in config.yml over-ride those in config.json and there's no way for the user to modify this.
\<perlpilot> veryrusty: moreover, the order those files are loaded is entirely determined by the order that Config::Any->extensions provides the extensions (which is not documented).
\<veryrusty> I've a set of D2 apps deployed via as (docker) containers. the containers include a set of "static" config, as yaml files. secrets are written to json by orchestration tools and mounted into the containers.
\<veryrusty> TIMTOWTDI applies, but that "just works".
\<perlpilot> veryrusty: until someone accidentally changes the order that Config::Any->extensions returns things or someone accidentally (or purposefully) names a key in your YAML file the same as one of the keys in your JSON file (the YAML file will take precedence)
\<perlpilot> veryrusty: Would it be onerous for you to change the JSON files to by my-production.json ?
\<perlpilot> er, environments/my-production.json
\<veryrusty> only that I have to change something that currently works
\<veryrusty> ( I'd also prefer a '_local' suffix than the 'my-' prefix )
\<perlpilot> aye, we could bikeshed the name all day  :)   I don't care one way or the other. 
\<perlpilot> I'm just after some consistency and a little more control.
\<perlpilot> for instance, we use YAML files for our config, so currently the *only* way to have some creds in a config file is to use something other than YAML  (or, use config.yaml and config.yml)
\<perlpilot> which just seems wrong
\<perlpilot> (and again, we can't know for sure without looking under the hood a little bit which order they will be loaded)
\<perlpilot> I'm fine looking under the hood and understanding whatever trade-offs there are, but then I have to document that for the rest of my team so they don't accidentally mess something up (or if they do, at least have a clue about what went wrong)
\<perlpilot> but then, it's also not just *my* team that has to do this, but everyone who uses Dancer2
\<perlpilot> (that is, re-discover how to store local config info and that they might have to do mix-n-match two different config file formats)

I'd prefer that Dancer have some clean, documented way to achieve the 2 main things I'm after rather than have everyone rediscover how to do it:
* deployment-specific configuration
* developer-specific configuration

**Comment by cromedome** [comment]
I tend to agree with @sukria on this point. We are adding too much complexity to the app by having the configuration dir, and I am not a fan of implementing it as such.

I agree with @perlpilot that the way it works now is an undocumented "feature", and if something changes in the way `Config::Any` works can potentially change the way configuration works in Dancer, causing apps to break due to no fault of our own. For that reason alone, we should tighten up the way we are processing config files.

I can see @veryrusty's point about not wanting to break existing apps, and @perlpilot's needs as well. I think there's a middle ground to be had between the two that doesn't involve moving to a configuration directory. I'll see what I can cook up tonight - a bit tied up for most of the day today.

Thanks for the patch, @perlpilot, and for getting the ball rolling on this.

**Comment by perlpilot** [comment]
@veryrusty I was just thinking about your comment to log when each file is merged.  If it told you what config items were merged and which took precedence, that would be quite useful.  Something like "Replacing config.yaml 'service_A_info' with value from environments/development.yaml".  Especially if the group does decide to use some sort of config.d directory.  

BTW, I think having a config.d directory makes for too many moving parts when config files are merged as they are currently. And performance could be negatively impacted if there were many files in this directory.  I'm more in favor of some relatively small number of well-defined places for Dancer to look for configuration information.

**Comment by cromedome** [comment]
Resolved by e9a633d0851f42fa5822151920180a40887a8dbc. Closing!

**Pull request closed without merging**
