### PR TITLE
Add "accept" header to supported routing match options

### PR DESCRIPTION
**Pull request by perlpunk**
It would be nice if one could route depending on the accept header (for example if it contains an API version).

### CODE REVIEW

**Comment by xsawyerx** [comment]
I personally don't like the matching options (a rarely-used feature, as far as I know), but this does make sense to add.

The only problem I have is that we haven't really discussed these options. They all seem to be HTTP headers, except `path_info`, which isn't. Also, other HTTP headers are not available, so I'm not sure what's really going on there.

@sukria, Could you comment on what the original intention was, and which direction you think it should go? Should all HTTP headers be supported? Is this a logical list rather than HTTP header-based?

@perlpunk, Is this disrupting you from still writing a path that checks the `accept` field and moves on if it isn't available?

    get '/' => sub {
        request->accept eq '...' or pass;
        ...
    };

**Comment by perlpunk** [comment]
@xsawyerx, I'm trying to write methods depending on the API version in the accept header.
Of course I can do it manually by adding my own layer which routes to the correct methods. I just wanted to avoid this ;-)
mojolicious for example supports routing in a very flexible way by defining a custom subroutine.
Dancer only supports a list of fields of the request, and I'm not sure why the list of fields should be artificially limited...

**Comment by xsawyerx** [comment]
So other than adding more fields, what else can we do to make it flexible?

**Comment by perlpunk** [comment]
I would suggest something like this:
```
    my $route_w_accept = Dancer2::Core::Route->new(
        method  => 'get',
        regexp  => '/',
        code    => sub {'options'},
        options => {
            'callback' => sub {
                my ($req) = @_;
                my $accept = $req->header('Accept');
                return 1 if $accept =~ m{foo/bar-v3};
                return 0;
            },
        },
    );
```
Works fine for me.

**Pull request closed without merging**
