### PR TITLE
change module requirement to allow Plack to be installed on Windows

### PR DESCRIPTION
**Pull request by sdondley**
Attempt at a fix for https://github.com/PerlDancer/Dancer2/issues/1483. After applying this patch locally, I was able to get Dancer2 installed on my Windows machine. (Note that there was a failing cookie test, however. I just commented that out but that commented out code is not in this patch).

### CODE REVIEW

**Comment by sdondley** [comment]
Just another note here, Plack will only fail to install with Test::Time if the `Cookie::Baker` module is not already installed.

**Comment by cromedome** [comment]
This is a toolchain issue, and not something I think we should solve in Dancer, so this gets :-1: from me. If you haven't already done so, it might be best to submit an issue to https://github.com/plack/Plack/issues

Perhaps you could add this information to the wiki so others affected by this might be able to find a solution to it?

**Comment by sdondley** [comment]
K, but not patching .appveyor will cause all those tests to fail.

**Comment by cromedome** [comment]
I am pondering the wisdom of cherry-picking that bit out. I am not a big fan of `--notest`.

**Comment by cromedome** [comment]
Closing as the original `Test::Time` issue has been resolved.

**Pull request closed without merging**
