### PR TITLE
Feature/request response headers

### PR DESCRIPTION
**Pull request by veryrusty**
A dose of JFDI for #1039  :wink: 

  * New response header keywords `response_header`, `response_headers`, `push_response_header`. Existing header keywords deprecated.
  * Adds new keyword for accessing request headers: `request_header` with simple test.
  * Updated docs

### CODE REVIEW

**Comment by xsawyerx** [comment]
I'm a bit worried about **another** deprecation notice close to when we're deprecating the old plugin interface. I don't want to overwhelm users. Can we comment those for now?

**Comment by SysPete** [comment]
:+1: for delaying deprecation notices especially with the number we're already seeing with P2.

**Comment by veryrusty** [comment]
I concur that there are enough changes happening with the upcoming merge of Plugin2.
 
Deprecation warnings commented out and flagged as a TODO after a period of stability.  :smile:

**Comment by xsawyerx** [comment]
:+1: from me.

@veryrusty :heart: 
@mickeyn would like to have your comment on this, please.

**Comment by mickeyn** [comment]
seems legit.

@veryrusty++

**Comment by cromedome** [comment]
:+1: from me as well. Thanks @veryrusty!

**Comment by veryrusty** [comment]
Rebased and merged as 431d8d8.  Thanks everyone!

**Comment by xsawyerx** [comment]
@veryrusty++ !

**Pull request closed without merging**
