### PR TITLE
added 5.22, 5.24 to .travis.yml

### PR DESCRIPTION
**Pull request by jacoby**
Noticed the .travis.yml file is two full releases behind.

### CODE REVIEW

**Comment by SysPete** [comment]
:+1: from me. Just wish I could work out where that Appveyor junk came from.

**Comment by racke** [comment]
:+1: from me as well. Right, got no idea what appveyor is and who added it to Dancer2.

**Comment by jacoby** [comment]
racke, appveyor is travis-cl for Windows, so if the module is run from a Win10 box, it'd be as tested as it would be on Linux.

Last week was the Perl Toolchain Summit, and it might have been turned on then. As with Travis, you log in as project owner and check/uncheck the project for testing.

**Comment by racke** [comment]
@jacoby - the setup for appveyor seems to be missing.

**Comment by jacoby** [comment]
Yeah, and I'm trying with a toy project to figure out what a decent setup file would be. Right now, I'm pulling 5.24 from chocolatey but haven't told it to install Dist::Zilla. 

I'd suggest someone play with it elsewhere and turn off the AV checks until then.  But  that's up to Sawyer.

**Comment by SysPete** [comment]
Many thanks @jacoby I'm going to have a play with this.

**Comment by jacoby** [comment]
Glad to help. I threw it together with a repo I hope to make a module soon. I hope this all gets used eventually.

**Comment by jacoby** [comment]
I think I'm missing one of the dzil *deps | cpan steps, but it builds!

**Comment by jacoby** [comment]
Hrmm. 5.26 isn't on Travis yet. It'll get there, I'm sure.

**Comment by cromedome** [comment]
:+1: from me. Merged! Even better, 5.26 is on Travis CI now :smile:

**Pull request merged**
