### PR TITLE
calling plugin_setting from plugins in plugins

### PR DESCRIPTION
**Pull request by hvoers**
Tested with Dancer2::Plugin::DBIC

### CODE REVIEW

**Comment by racke** [comment]
Please reduce your patch to the changes in _plugin_setting.

**Comment by hvoers** [comment]
I am following GitGuide.md

I am not patching '_plugin_setting'.

This is a patch of Dancer2::Plugin.pm

**Comment by racke** [comment]
Yes, but remove the POD changes from your patch.

**Comment by hvoers** [comment]
OK. I think you mean not my POD but the other pod that by magic appeared in the path?
Like =method ---> =head ?

**Comment by racke** [comment]
Yes, DistZilla replaces =method and adds version when you build the package.

**Comment by hvoers** [comment]
Ok. Discard this.
I will do 
GitGuide.md
from scratch ... :(

**Pull request closed without merging**
