### PR TITLE
disable scheduled GitHub action on forks

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by racke** [comment]
Can you please elaborate on this change, @szabgab ?

**Comment by szabgab** [comment]
In the previous version of the Github Actions the job is executed on push events, on pull requests, and also using the scheduler. This worked both in the central repository and on every fork as well. This pull request disables the scheduled execution on the forks. Or at least I hope it does that.

**Comment by racke** [comment]
OK, but what is wrong with running the action on your fork? Doesn't that need to enabled explicitly like for Travis?

**Comment by szabgab** [comment]
AFAIK it is enabled by default.

**Comment by racke** [comment]
Yes, that is true. Why is that a bad thing? With your change I can't run the actions on my fork if I want to.

**Comment by szabgab** [comment]
This change, if I am not mistaken, only disables the scheduled job on the forks. It will still run all the jobs hen you push new code to your fork.

**Comment by racke** [comment]
Yes, it still works on the fork when pushing commits there. :+1:

**Comment by SysPete** [comment]
:+1:

**Comment by cromedome** [comment]
Merged, thanks!

**Pull request closed without merging**
