### PR TITLE
Route params with types

### PR DESCRIPTION
**Pull request by SysPete**
Hopefully this PR will generate some discussion as to how we would like to proceed with typed params. This code his been around for > 2 years and PR created after I was pinged about it by @cromedome.

Allows types to be specified in route param definitions allowing such things as:

```
get '/thing/:id[Int]' => sub {};

# if not Int then perhaps a Num...
get '/thing/:id[Num]' => sub {};
```

In original issue @yanick suggested:
> Interesting venue to explore. We could even do something like (off-the-cuff pseudo-code below)

```
subtype UserId => as Int => validate { };  # don't remember the real Types::Tiny syntax

get '/api/user/!UserId' => sub { 
  ...;
  # dancer magic would use the type name to populate the right param name
  param('UserId'); 
};
```

This is not currently possible in current implementation but could be added later.

See also @xsawyerx's [Dancer2::Plugin::ParamTypes](https://metacpan.org/pod/Dancer2::Plugin::ParamTypes).

### CODE REVIEW

**Comment by cromedome** [comment]
Disclaimer: I have not yet had a chance to experiment with this, my feedback is based solely on looking through the PR without running tests or writing code.

I *really* like how easy this PR makes it for the developer to add types to their parameters in Dancer2. Being able to have Dancer2 validate the parameters as they are passed into the application will help to eliminate a lot of boilerplate code that does just that (at least that's the case from my own code). Pretty excited to clone this and try to adapt a couple of my existing apps to it. This goes a long way towards making things easy and fun again, as we like to preach.

It's my hope that with an eventual inclusion of this that @yanick's suggestion won't be too far behind ;)

I'll have more comments once I get a chance to work with this throughout the week. Thanks @SysPete!

**Comment by cromedome** [comment]
For the most part, this has been awesome. A couple of weird things that I have run into however:

I have a route that ends with an optional parameter (example based on something at `$work`):
```
get '/pdf/:product[StrMatch[qr{(foo|bar|baz)}]]/:state[StrMatch[qr{(\w{2})}]]/:force[StrMatch[qr{([fxplt])}]]?' => sub {
    return "Hello! " . route_parameters->{ product } . " / " . 
        route_parameters->{ state } . 
        ' / force ' . route_parameters->{ force };
};
```
In this example, the URL `http://localhost:5000/pdf/bar/FL/f` matches, but `http://localhost:5000/pdf/bar/FL/` and `http://localhost:5000/pdf/bar/FL` does not (to be fair, I expected the latter would not).

Originally, the last parameter was optional, and this was handled via the regex:
```
get '/pdf/:product[StrMatch[qr{(foo|bar|baz)}]]/:state[StrMatch[qr{(\w{2})}]]/:force[StrMatch[qr{([fxplt]?)}]]' => sub {
    return "Hello! " . route_parameters->{ product } . " / " . 
        route_parameters->{ state } . 
        ' / force ' . route_parameters->{ force };
};
```
This, however, doesn't compile: `Error while loading ~/TestApp/bin/app.psgi: Expected R_BRACKET; got MYSTERY at ~/perl5/perlbrew/perls/dancer-5.28.0/lib/site_perl/5.28.0/Type/Parser.pm line 391.'`

I intend to investigate further. Posting this here for the record, and in case you get to it before I can.

Thanks! Really liking this so far.

**Comment by SysPete** [comment]
`strict_typed_params` turned out to be a bad idea so I've removed it. I have now squashed all commits to get rid of a pile of noise and consider this PR ready for review.

This comment https://github.com/perldancer/dancer2/issues/1127#issuecomment-202900429 from @yanick is not yet addressed and I will look at adding that as a later enhancement.

**Comment by cromedome** [comment]
I just spent some time reviewing this again, and I am really happy with it. My earlier issue is resolved, and I haven't run into any other bugs or unexpected behavior. This gets a big :+1: from me! (sorry it took so long to get back to it).

Fellow Dancers - What say ye? :smile:

**Comment by yanick** [comment]
Let's.

**Comment by cromedome** [comment]
It's go time! Thanks @SysPete!

**Pull request merged**
