### PR TITLE
Fix plugin pod

### PR DESCRIPTION
**Pull request by cromedome**
This fixes Issue #990. Plugin Pod no longer includes deprecated functionality.

### CODE REVIEW

**Comment by ambs** [comment]
Can you squash the three commits in one?
(see for example http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

Other than that, :+1: 

(let me know if you need help with the squash)

**Comment by cromedome** [comment]
Actually, I had just wanted to send you the most recent commit. The other two were part of a pull request yesterday.

What did I mess up?

Jason A. Crome / CromeDome
crome-plated: Web Development and Custom Programming
http://crome-plated.com

**Comment by ambs** [comment]
Not sure. Know how to fix, no idea what you did wrong :)

**Comment by cromedome** [comment]
Give me a few, I will fix and resubmit.

Jason A. Crome / CromeDome
crome-plated: Web Development and Custom Programming
http://crome-plated.com

**Pull request closed without merging**
