### PR TITLE
document exporting the utf8 pragma

### LINKED ISSUE #1122: Dancer2 messes my encoding
Running the following UTF-8 encoded source file:

    #!/usr/bin/perl -l
    print 'février';
    use Dancer2;
    print 'février';

Produces the following results:

    février
    f�vrier

hexdump reveals that “�” is actually “\xe9”, which is latin1 for “é”.

A grep through Dancer2’s source reveals the responsible line:

    $clean_import
        or $_->import::into($caller) for qw<strict warnings utf8>;

Please don’t do this. Silently messing with your caller’s encoding is never a good idea.

Of course, removing it now risks breaking some callers, so instead I suggest documenting it. Dancer2::Manual currently says:

    strict and warnings pragmas are also imported with Dancer2

It should instead say:

    strict, warnings *and utf8* pragmas are also imported with Dancer2

That would have saved me hours of debugging.

### PR DESCRIPTION
**Pull request by Grimy**
Fixes #1122

### CODE REVIEW

**Comment by veryrusty** [comment]
This looks good, matching the documentation for the `:nopragmas` import flag.  :+1:

**Comment by SysPete** [comment]
:+1: Agree: doc fix essential.

**Comment by veryrusty** [comment]
Checked the new docs draft in #1069. The import of the utf8 pragma has been noted there.

**Comment by veryrusty** [comment]
Merged. @Grimy++ Thanks for the Pr!

**Pull request merged**
