### PR TITLE
Improve docs about params

### PR DESCRIPTION
**Pull request by pdl**
Apropos Kadir's question to the users list, I suggest a number of changes to the documentation of `params` and friends, to make the merge behaviour (and its dangers) clearer.

### CODE REVIEW

**Comment by cromedome** [comment]
Awesome doc patch! :+1: from me. Thanks!

**Comment by xsawyerx** [comment]
Definite :+1: from me as well.

**Comment by SysPete** [comment]
:+1: also.

**Comment by cromedome** [comment]
Merged. Thanks for the clarification and contribution!

**Pull request merged**
