### PR TITLE
change <tt> to <span> in skel

### PR DESCRIPTION
**Pull request by jasonblewis**
The html `<tt>` tag is obsolete in html5, use `<span>`
instead for monospaced text

### CODE REVIEW

**Comment by xsawyerx** [comment]
:+1: from me.

**Comment by veryrusty** [comment]
:+1: from me!

( I noted the text isn't left aligned at the bottom of the diff .. a pedant would fix that when merging /me looks at the reflection in his monitor ;)

**Comment by veryrusty** [comment]
Merged as 14cedf1. Converted the tabs to spaces in the template, and added Jason to the list of contributors. Woot!

Thanks @jasonblewis !

**Comment by xsawyerx** [comment]
@jasonblewis++
@veryrusty++

**Pull request closed without merging**
