### PR TITLE
Rename "show_error" to "show_stacktrace"

### PR DESCRIPTION
**Pull request by valerycodes**

### CODE REVIEW

**Comment by veryrusty** [comment]
Hey @valerycodes & @krysy. Thanks for the pull request.

These are two *very* large diffs to work through, with lots of lines of change that seem unrelated to the issue being solved.

Would it be possibly to cut them down into smaller commits (`git add -p` is very useful), or rebase against the current master from this repo? Feel free to ask for help if needed :smile:

**Comment by xsawyerx** [comment]
No comments. I vote for closing this.

**Comment by SysPete** [comment]
I agree with closing this. We've had `show_errors` for ever and I don't see the advantage or fiddling with config param names.

**Comment by xsawyerx** [comment]
Two votes for closing.

**Pull request closed without merging**
