### PR TITLE
add Git Guide to a new section for listing project development resources

### PR DESCRIPTION
**Pull request by sdondley**
My first commit to an open source project via GitHub. I'm not sure if I'm doing this right. Feel free to scream at me if I've screwed it up. :)

This is to address the issue created at https://github.com/PerlDancer/Dancer2/issues/1407

I added a new section to the README.mkdn file for Project Development to list resources for those interested in contributing to the project. For now, it contains only the Git Guide.

### CODE REVIEW

**Comment by sdondley** [comment]
Looks like a check failed. Is this something I can fix?

**Comment by racke** [comment]
Forget about the App Veyor check - this check isn't reliable. My remarks:

I would not use a separate section - it is fine at last bullet in the Documentation Index (IMHO).

Otherwise it looks good beside the duplicated "the the". Please fix that in a commit and push it.

**Comment by sdondley** [comment]
Oh, and forgive my ignorance, but how do I properly make a pull request on top of another pull request? I'm still on branch `pr/docs` in my local repository. Do I just make the change and do a new pull request like I did with the original or is there some way to modify the existing one? I'm not very practiced with using github. Thanks.

**Comment by racke** [comment]
@sdondley just push commits from your local repository to Github to update your PR.

Concerning your reasoning, I would like to ask other developers for their opinion.

**Comment by cromedome** [comment]
I like your reasoning, @sdondley, but my inner editor tells me that we aren't supposed to have lists with only one bullet point (my senior English teacher would be proud of me for remembering that).

In all honesty, however, I don't have that strong an opinion, and I am going to :+1: your PR. If there are more requests to move this to the documentation index list though, I do request that you move it there.

Thank you for this! We appreciate the contribution!

**Comment by sdondley** [comment]
Well, maybe we can find other developer resources to add to the list like Gabor's interview with you and Sawyer. :) Seriously, though, if you think of other things can be added to the list, let me know.

I'm very excited by the Dancer2 project. Please let me know how I can help more with the documentation. It will help me learn. Feel free to assign new tasks to me.

**Comment by cromedome** [comment]
That was the other part of comment that I forgot to add! More resources are good too. Please feel free to add a link to my interview there. I think Gabor might have some other Dancer-related articles worth pointing to as well.

**Comment by sdondley** [comment]
Alight, I added a couple of other resources. I decided not to put links to the interviews out of fear of bruising some egos. :)

Those seems like great resources that should go on the website, though. I'd be interested in helping out with the website. Who do I talk to about that?

**Comment by sdondley** [comment]
I'm guessing these failures can be ignored for POD commits?

**Comment by cromedome** [comment]
:+1: Merged - thanks!

**Pull request closed without merging**
