### PR TITLE
A few tweaks to the manual

### PR DESCRIPTION
**Pull request by bigpresh**
A few simple doco tweaks in the manual - mostly just adding cross-linking.

### CODE REVIEW

**Comment by cromedome** [comment]
:+1: Thanks, @bigpresh!

**Comment by xsawyerx** [comment]
I had rewritten the Manual in #1069 and I want to merge this week. Any chance you could take a look if the bits you added here are missing there?

(When rebasing it yesterday I noticed one incident in which something I added was also added to the doc from the time I branched off, so it has happened at least once before.)

**Comment by bigpresh** [comment]
Let's get #1069 merged, then I'll re-visit this PR and re-apply the tweaks I made, if they still make sense.

**Comment by SysPete** [comment]
Closing since this was merged as part of v0.206000 via ae3abfcaf0be36f4eb2deee0ff5765375d620b81

**Pull request closed without merging**
