### PR TITLE
Fix warning "Odd number of elements in anonymous hash" (loses params)

### PR DESCRIPTION
**Pull request by basbloemsaat**
If a route with an optional argument was called without the argument, eg.
```
get "/app/?:arg?"
```
was called as
```
GET /app
```
a warning "Odd number of elements in anonymous hash at .../Dancer2/Core/Request.pm line 345." was produced. This was caused by _decode on undef returned a null and the result is parsed in list context. This trivial change prevents this from occurring.

This also causes the params hash to be mangled. Eg.
```
get "/app/:a/:b/?:b?"
```
Called as
```
GET /app/1/2
```
has a high chance of losing params a and b. So any API implemented using optional params is probably affected.

### CODE REVIEW

**Comment by veryrusty** [comment]
Thanks for the Pr @basbloemsaat !

We aim to maintain perl 5.8 compatibility; any chance you can rework to not use the defined-or operator?

**Comment by basbloemsaat** [comment]
Will do

**Comment by basbloemsaat** [comment]
Travis failing seems to be upstream btw, tests related to this are ok

**Comment by xsawyerx** [comment]
Merged in https://github.com/PerlDancer/Dancer2/commit/64e0befe3eca8513ef15fb0f2f7572c5eb8886ea, thanks! :+1:

**Pull request closed without merging**
