### PR TITLE
Fix nonsensical documentation

### PR DESCRIPTION
**Pull request by tomhukins**
It's still hard to read, but better than it was..

### CODE REVIEW

**Comment by cromedome** [comment]
:+1: Thank you!

**Comment by SysPete** [comment]
:+1: Thank you @tomhukins!

**Comment by cromedome** [comment]
Merged, thanks again!

**Comment by tomhukins** [comment]
I apologise if I'm missing something, but I don't see this change on the master branch.  I still see the old wording in `lib/Dancer2/Config.pod` and on https://metacpan.org/pod/Dancer2::Config so I suspect you forgot to merge this change.

**Comment by cromedome** [comment]
I'm not sure what happened but I think this is in master now. Sorry about that.

**Pull request closed without merging**
