### PR TITLE
Feature: use Safe instead of eval

### PR DESCRIPTION
**Pull request by zurborg**
Use safe compartment to prohibit unsafe code in deserializer

### CODE REVIEW

**Comment by veryrusty** [comment]
@zurborg Thanks for the Pr!

Looks good to me. We'll need to add `Safe` to the dependency list in `dist.ini`.

**Comment by hvoers** [comment]
Isn't Safe just a Core module?

**Comment by veryrusty** [comment]
@hvoers so it is :)  I missed that Safe is a dual-life module.. I should have had coffee *before* looking at the Pr ;)

**Comment by veryrusty** [comment]
Explicitly giving this a :+1:  Anyone else ?

**Comment by zurborg** [comment]
`dzil listdeps` returns `Safe` - IMHO there is no need to add `Safe` to the dependency list by hand.

**Comment by xsawyerx** [comment]
:+1:

**Comment by xsawyerx** [comment]
Merged, thanks! :+1:

**Pull request closed without merging**
