### PR TITLE
update POD for `match`, which takes a request object

### LINKED ISSUE #1312: Documentation for Dancer2::Core::Route->match is incorrect
The documentation says

```
my $match = $route->match( get => '/hello/sukria' );
```

but the code reads
```
sub match {
    my ( $self, $request ) = @_;
    ...
    my @values = $request->dispatch_path =~ $self->regexp;
```

so the argument to match must be a Dancer2::Core::Request object

### PR DESCRIPTION
**Pull request by simbabque**
Fixes #1312

### CODE REVIEW

**Comment by racke** [comment]
Looks good to me 👍

**Comment by simbabque** [comment]
Are the failing appveyor tests a recent occurrence? I've had it in my other PR as well. But docfixes will not account for their boxes timing out I guess.

**Comment by racke** [comment]
Yeah it doesn't seem really reliable.

**Comment by SysPete** [comment]
Thanks @simbabque 👍

**Comment by cromedome** [comment]
@simbabque I haven't had a chance to check into Appveyor yet. I am not overly familiar with it yet either.

**Comment by cromedome** [comment]
Merged, thanks!

**Pull request closed without merging**
