### PR TITLE
added show_privates option

### PR DESCRIPTION
**Pull request by ambs**
The added docs explain what this patch does. I must say it is very handy on some situations. it would be great if it could be merged.

### CODE REVIEW

**Comment by SysPete** [comment]
@ambs could we perhaps change the name to `show_private_variables`? Only a few more chars to type and will prevent quite some sniggering :smile: . Otherwise :+1: from me.

**Comment by ambs** [comment]
Sure :-)

**Comment by ambs** [comment]
any other :+1: so I can merge this? O:-) it is something I need in a current project ;-)

**Comment by racke** [comment]
There is also a typo in there: `disble`

**Comment by cromedome** [comment]
:+1: from me if the option name is changed and the typo fixed :)

**Comment by ambs** [comment]
My mac has a difficult key 'a', sorry. Will fix and merge.

**Pull request closed without merging**
