### PR TITLE
Add documentation index to dancer2 pod

### PR DESCRIPTION
**Pull request by bentglasstube**
Per the discussion on #863, this adds links to the full documentation to the documentation for dancer2 so that it is more easily discoverable on case insensitive file systems.

### CODE REVIEW

**Comment by xsawyerx** [comment]
@bentglasstube :+1: from me.

I think we can merge this.

**Comment by xsawyerx** [comment]
This should be merged before #1069 and #1069 should be rebased off this.

**Comment by cromedome** [comment]
:+1: for the patch and for applying it before #1069. Thanks @bentglasstube!

**Comment by ambs** [comment]
for what I understood, this one was good to go... so... gone.

**Pull request closed without merging**
