### PR TITLE
Add Test::Deep dependency for testing

### PR DESCRIPTION
**Pull request by nunorc**
Some new test files require Test::Deep.

### CODE REVIEW

**Comment by SysPete** [comment]
Thanks @nunorc - good catch.

I think I'd prefer not to add the dep since this is only in the new plugin2 tests. I'll cook up a new PR which drops Test::Deep then we see what other devs prefer.

**Comment by SysPete** [comment]
So the question is do we add the build dep on Test::Deep or use modified tests as per #1177?

**Comment by veryrusty** [comment]
@nunorc++ nice catch.

Since the changes to remove Test::Deep are fairly minimal, I'd prefer to see the test dependency removed.

**Comment by xsawyerx** [comment]
@nunorc++

I agree in just removing `Test::Deep`.

**Comment by nunorc** [comment]
Either option seems fine, as long as we can build an successfully test the package from a clean environment.

I'm closing this request if favor of https://github.com/PerlDancer/Dancer2/pull/1177. Thank you.

**Pull request closed without merging**
