### PR TITLE
pr/send as plain

### PR DESCRIPTION
**Pull request by sdondley**
For issue #1418 

My first contribution to core. Critiques welcome.

### CODE REVIEW

**Comment by racke** [comment]
You leaked commits from other PR. Please provide fresh PR with just the `send_as` patch. Create branch from pristine master.

**Comment by sdondley** [comment]
Sorry. I'm pretty much a newb to git. I've only dabbled with it to get the gist of what it does. Anything beyond basic commits and I'm lost.

So after I reset to master, how do I get the work from my pr/send_as_plain branch onto a new branch without having to redo my work?

**Comment by racke** [comment]
Back to master:

`git checkout master`

Create fresh branch:
`
git checkout -b pr/send_as_plain_2nd_try`

Copy commit to the fresh branch:

`git cherry-pick 7346076ba2f4e4fda031693704af2e0c36da3343`

**Comment by racke** [comment]
Closing in favour of #1422

**Pull request closed without merging**
