### PR TITLE
Perl is picky about brackets matching

### PR DESCRIPTION
**Pull request by guest20**
Typo fix.

### CODE REVIEW

**Comment by veryrusty** [comment]
:+1: Thanks @guest20 !

**Comment by racke** [comment]
👍

**Comment by veryrusty** [comment]
Merged into master in commit 503acf3f.  Thanks again @guest20!

We like to acknowledge our contributors to the Dancer2 codebase. @guest20 you are more than welcome to email myself ( `russellj` at `cpan` dot `org` ) or @cromedome to add your preferred name to the list of authors!

**Comment by veryrusty** [comment]
.. and closing PR 👯

**Pull request closed without merging**
