### PR TITLE
Deployment documentation improvements

### PR DESCRIPTION
**Pull request by abeverley**
This PR primarily provides some additional clarity to the Apache CGI and FastCGI sections. It also contains some other tidying up, see the individual commits for details.

### CODE REVIEW

**Comment by SysPete** [comment]
:+1: A huge improvement for Apache deployment.

**Comment by xsawyerx** [comment]
:+1: ready for merge!

**Comment by cromedome** [comment]
:+1:

**Comment by xsawyerx** [comment]
Merged, thanks! :+1:

**Pull request closed without merging**
