### PR TITLE
Feature/xs cookies

### PR DESCRIPTION
**Pull request by SysPete**
This is a tracker PR to enable issues to be discussed regarding use of HTTP::XSCookies

### CODE REVIEW

**Comment by SysPete** [comment]
See https://github.com/PerlDancer/Dancer2/issues/1087#issuecomment-176776693 for results of performance comparison.

**Comment by SysPete** [comment]
Old branch was getting messy so I've flattened the commits into 4 individual parts. I'd really appreciate review now as I'm pretty much finished.

**Comment by SysPete** [comment]
One problem exists with current code - see https://github.com/PerlDancer/Dancer2/issues/1087#issuecomment-177974835

**Comment by SysPete** [comment]
Assuming travis does its stuff the final issue I had with this PR is now fixed so I reckon it is ready for merge.

**Comment by xsawyerx** [comment]
I pushed some changes into branch `feature/xs_cookies` in PerlDancer. Could you pull and push?

**Comment by SysPete** [comment]
@xsawyerx pull/push done (and rebased against master)

**Comment by SysPete** [comment]
@PerlDancer this should be ready to merge so any :+1: ? Maybe @cromedome would like me to flatten it a little?

**Comment by cromedome** [comment]
:+1: Let's merge soon!

The commit history looks fine to me. Only one commit I would considering flattening... doesn't seem worth the effort.

**Comment by xsawyerx** [comment]
:+1:

**Comment by cromedome** [comment]
Merged in f41de8989cc630cf999eae2dd15ad8768715c8bb. Thanks!

**Pull request closed without merging**
