### PR TITLE
Feature/log config files

### PR DESCRIPTION
**Pull request by 1nickt**

### CODE REVIEW

**Comment by cromedome** [comment]
Thanks for the revision. This also gets a :+1: from me.

**Comment by racke** [comment]
The commit history of this pull request isn't clean. It should only have two commits.

**Comment by cromedome** [comment]
Nice catch, @racke. Was too focused on code change. Thank you.

**Comment by 1nickt** [comment]
> The commit history of this pull request isn't clean. It should only have two commits.

Thank you, raising a new PR and closing this one.

**Pull request closed without merging**
