### PR TITLE
Feature/find plugin

### PR DESCRIPTION
**Pull request by xsawyerx**
Per the conversation with @yanick.

This purposefully doesn't error out, so the plugin developer can decide what kind of error to throw.

I have implemented it both in the App and the Plugin, just in case.

I need it approved quickly, so I can add this to an article.

### CODE REVIEW

**Comment by yanick** [comment]
looks good to me. ==b o.o

**Comment by xsawyerx** [comment]
Added documentation. @SysPete, any chance for a :+1: ?

**Comment by racke** [comment]
:+1:

**Comment by SysPete** [comment]
:+1:

**Comment by xsawyerx** [comment]
Merged!

**Pull request closed without merging**
