### PR TITLE
No warning if optional megasplat not present.

### PR DESCRIPTION
**Pull request by bigpresh**
This is the same bug reported in D1 as PerlDancer/Dancer#1144 - the bug was
also present in D2.

The D1 fix was in commit PerlDancer/Dancer@a5e54dc

### CODE REVIEW

**Comment by veryrusty** [comment]
Looks good. Any chance for adding a test?  (`t/classes/Dancer2-Core-Route/match.t` is probably the best place)

**Comment by bigpresh** [comment]
Right, there's tests for the behaviour of optional megasplats with & without a value - they pass before and after this change.

I was wondering if we should have all test scripts check for the absence of warnings too automatically, but it wouldn't have caught this, as we weren't testing an optional megasplat without a value, it seems.

**Comment by veryrusty** [comment]
I'd normally use `Test::Warnings` to test for such warnings (or the lack there of).  We don't currently have it as a test dependency. Anyone got any thoughts on using `Test::Warnings` ?

**Comment by xsawyerx** [comment]
@veryrusty Don't we use `Capture::Tiny`? Let me take a look at this today.

**Comment by xsawyerx** [comment]
Okay, we *do* use `Capture::Tiny`, which means we can test warnings that way.

**Comment by xsawyerx** [comment]
Oh, and :+1: for the PR. @bigpresh++

**Comment by veryrusty** [comment]
:+1: I'll merge with the Capture::Tiny tests for warnings.

**Comment by veryrusty** [comment]
Merged in 74afc7c. @bigpresh++

**Comment by bigpresh** [comment]
Cheers!

**Comment by Relequestual** [comment]
\o/

**Pull request closed without merging**
