### PR TITLE
Import plugins with Dancer2::Plugins into application

### PR DESCRIPTION
**Pull request by zurborg**
This feature request allows everyone to use `Dancer2::Plugins` as plugin loader

No big deal, just syntactic sugar.

``` perl
use Dancer2::Plugins qw/
    Adapter
    Ajax
    Auth::Tiny
/;
```

I had to workaround `Import::Into` ... and came to a crazy solution:

``` perl
eval("package $caller { use $plugin } ");
```

Looks weird, is weird, but works good.

### CODE REVIEW

**Comment by xsawyerx** [comment]
:+1: Neat idea!

Why did you have to work around `Import::Into`? Couldn't you have you used it directly?

**Comment by zurborg** [comment]
I've done some experiments with Import::Into but that didn't work properly. I think there is an issue with on_plugin_import. So instead fixing this issue I found out that my workaround could help. But the `package $namespace { ... }` syntax seems not known to older perl versions (previous 5.16? uhm...) and that should be fixed, indeed.

**Comment by xsawyerx** [comment]
@zurborg I'll try implementing it with `Import::Into` again. Maybe I'll get lucky.

**Comment by xsawyerx** [comment]
It seems like this cannot be implemented using Import::Into.

The form of `package $name { ... }` is relatively new and we want to remain 5.8.x compatible, so if you could revise that to `package $name; use $plugin_class;` - that would be great.

**Comment by preaction** [comment]
How were you using Import::Into? Your problems may have something to do with https://github.com/PerlDancer/Dancer2/pull/1136

**Comment by xsawyerx** [comment]
I don't remember. I'll try again and report back.

**Comment by SysPete** [comment]
:+1: Since this is sugar that has no impact on any other D2 code I'm in favour of merging this. Also, quite a neat thing to have available when you're importing a pile of plugins.

**Comment by cromedome** [comment]
I like this, thanks! 👍

**Comment by cromedome** [comment]
I cannot get the tests to run for this. Not sure if it is an issue with the feature or the tests. I will investigate.

**Comment by xsawyerx** [comment]
Reviewing it many years later, I'm not a fan anymore, for two reasons:

1. It makes code less grep-able and difficult to statically analyze
2. It's a hack to just avoid writing `use Dancer2::Plugin::` and that seems like a hack that makes code less maintainable for a marginal gain.

I'm sorry for the work you put in, but I suggest we don't merge this.

**Comment by zurborg** [comment]
No problem - it was just a hack, nothing important :-)

**Pull request closed without merging**
