### PR TITLE
RFC: Allow prototypes for keywords:

### PR DESCRIPTION
**Pull request by xsawyerx**
This is just a quick thing I put together when discussing some
syntax for prefix setups with Aristotle. Just an idea and an
implementation we can discuss.

I don't know how important it is to allow prototypes, but if it
doesn't take anything from us, why not.

This breaks the plugin_syntax.t test - I didn't check why.

### CODE REVIEW

**Comment by xsawyerx** [comment]
No one had complaints so I'm merging it. I would like the streaming support to use it for shinier syntax.

**Comment by xsawyerx** [comment]
Bah, I forgot it broke stuff.

**Comment by xsawyerx** [comment]
Rebased and pushed force.

**Comment by veryrusty** [comment]
As this evals a string to get the coderef, it should be possible to include the idea from #819, to reduce one level of indirection in the compiled subs; something like
```
    my $compiled_code = eval qq{
        sub($prototype) {
          if ( ! \$opts->{'is_global'} ) {
            \$self->app->has_request or
              croak "Function '\$keyword' must be called from a route handler";
          }
          \$self->$keyword(\@_);
        };
    };
```

**Comment by veryrusty** [comment]
The test failure is due to the import into the plugin's namespace of the DSL keywords, the ones with the deprecation notice to use `$dsl->keyword` instead.

`t/lib/PluginWithImport.pm` currently has
```
use strict;
use warnings;

use Dancer2;
use Dancer2::Plugin;
...
```
which imports the DSL symbols once with the prototypes (`use Dancer2`), and then attempts to import the wrapped versions without prototypes.

It's simple to remove the `use Dancer2;` line to make the test pass. **BUT** I've done a quick scan of plugins on cpan/github and this will cause downstream breakage as there are more than a handful of plugins that do this. eg
  * on cpan: BrowserDetect, Sixpack, Email
  * github: Interchange6 (semi random example to ping @racke for feedback )

I'm not sure what the best way to tackle this. :(

**Comment by xsawyerx** [comment]
I like the improved `eval`. :+1:

**Comment by xsawyerx** [comment]
Although, we might be able to do the condition outside, so it's only run when compiling.

**Comment by hvoers** [comment]
On Sat, 7 Feb 2015, Russell Jenkins wrote:

> The test failure is due to the import into the plugin's namespace of the DSL keywords, the ones with the deprecation notice to use $dsl->keyword instead.
> 
> t/lib/PluginWithImport.pm currently has
> 
> use strict;
> use warnings;
> 
> use Dancer2;
> use Dancer2::Plugin;
> ...
> 
> which imports the DSL symbols once with the prototypes (use Dancer2), and then attempts to import the wrapped versions without prototypes.
> 
> It's simple to remove the use Dancer2; line to make the test pass. BUT I've done a quick scan of plugins on cpan/github and this will cause downstream breakage as there are
> more than a handful of plugins that do this. eg
>
>  *  on cpan: BrowserDetect, Sixpack, Email

D*::Plugin::Email is one of the plugins that I can use with D1 and not with D2.

>  *  github: Interchange6 (semi random example to ping @racke for feedback )

See also: https://github.com/PerlDancer/Dancer2/issues/754

> I'm not sure what the best way to tackle this. :(

What about:

http://lists.preshweb.co.uk/pipermail/dancer-users/2015-February/004358.html

-- 
Henk

**Comment by veryrusty** [comment]
I have a simple solution.  :smile:

I'm putting together a new Pr that also includes allowing plugins to add prototypes to their registered keywords. Just some test cases to go :)

**Comment by veryrusty** [comment]
#848 is an alternative to this Pr. with passing tests :)

**Comment by xsawyerx** [comment]
#848 was merged, we can close this.

**Pull request closed without merging**
