### PR TITLE
add example of setting a title

### PR DESCRIPTION
**Pull request by jasonblewis**
I think it would be nice to show how to set the title of the html page in the generated app

### CODE REVIEW

**Comment by racke** [comment]
Good idea :-) :+1:

**Comment by xsawyerx** [comment]
While I think it's a nice example, it also turns the global example into a more specific use.

I think we would have a greater value of making the scaffolding script allow different profiles (there's a ticket for it) and then have one of them contain a title, amongst other stuff.

**Comment by jasonblewis** [comment]
maybe that example isn't great but i think it would be valuable to have in the default template, an example of setting a variable in the app, and using it in the template

**Comment by xsawyerx** [comment]
Agreed.

**Comment by jasonblewis** [comment]
@xsawyerx is refering to https://github.com/PerlDancer/Dancer2/issues/1115

**Comment by xsawyerx** [comment]
Merged!

**Pull request closed without merging**
