### PR TITLE
calling plugins from plugins

### PR DESCRIPTION
**Pull request by hvoers**

### CODE REVIEW

**Comment by xsawyerx** [comment]
We're currently trying to overhaul the entire plugin system. We have two competing implementations (one by @yanick and one by @veryrusty) and I hope we will be able to resolve them soon enough.

**Comment by hvoers** [comment]
Should I stop working on Dancer2::Plugin::Auth::Extensible and just wait?
Do you have an ETA?

**Comment by veryrusty** [comment]
@hvoers Is there any code in Plugin::Auth::Extensible that could be used for testing (or generating tests for) plugins calling plugins ?

**Comment by hvoers** [comment]
Yes, Dancer2/Plugin/Auth/Extensible/Provider/Database.pm
Try test dynamic config of Dancer2::Plugin::Database like Dancer2::Plugin::DBIC does.

With this patch (#865) and https://github.com/ironcamel/Dancer2-Plugin-DBIC/pull/9
I can use the 'schema' keyword in a D2::P::A::E::Provider with the correct schema_name.

I didn't got D2::P::A::E::P::Database to work with even one database_name.

**Comment by av8r** [comment]
Any updates ?
Any code to test ?
Ty

**Comment by hvoers** [comment]
On Fri, 25 Sep 2015, av8r wrote:

> Any updates ?

I am converting my plugins to normal modules
that just import my DSL words as normal functions.

These normal functions can use common parts of
plugin wrappers like  ::Plugin::DBIC
I now use the 'schema' DSL word from DBICx::Sugar

**Comment by xsawyerx** [comment]
Am I right that this issue will be resolved as soon as we release D2P2?

@hvoers please correct me if I misunderstood.

**Comment by hvoers** [comment]
@xsawyerx  If D2P2 solves the problems for Dancer2::Plugin::Auth::Extensible providers
then I am happy.

Note: This PR is a year old. I have not used a Dancer2::Plugin since. Let's close this PR.

**Comment by xsawyerx** [comment]
@hvoers++ thanks!

**Pull request closed without merging**
