### PR TITLE
Fixed link to flaskr tutorial.

### PR DESCRIPTION
**Pull request by manwar**
Hi @cromedome 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by tomhukins** [comment]
This doesn't look like a proper fix to me.  I'd expect to the link to point at the top level at https://github.com/pallets/flask not the https://github.com/pallets/flask/tree/master/examples/tutorial/flaskr subdirectory you linked to.

**Comment by manwar** [comment]
Updated PR and rebase it.

**Comment by cromedome** [comment]
:+1: Thank you!

**Comment by cromedome** [comment]
Merged, thank you!

**Pull request closed without merging**
