### PR TITLE
Changes accordingly with new Plack release (mst++)

### PR DESCRIPTION
**Pull request by ambs**
It seems something changed on last Plack. This fixes it. Thanks to @shadowcat-mst

### CODE REVIEW

**Comment by ambs** [comment]
Hopefully fixes #921 with less code

**Comment by veryrusty** [comment]
"something changed" is somewhat vague..

Plack moved to use HTTP::Headers::Fast as its more performant. We should do the same, which is what #922 is about. I'd be happy to see this combined into #922 if a few extra characters of code is all we are concerned about.

**Comment by veryrusty** [comment]
Combined this into #922. The bless + isa check is cleaner than the regex update. Thanks @ambs!

**Comment by ambs** [comment]
Sorry, @shadowcat-mst asked me to create a fix, and was in a hurry. Really did not have time to make it better explanation!

**Comment by ambs** [comment]
@veryrusty++ as usual

**Pull request closed without merging**
