### PR TITLE
Tutorial & Documentation Updated

### PR DESCRIPTION
**Pull request by sakshee3**
Updated the Tutorial
- Added the command to run the _dancer.pl_ script

This is the problem one faces when he/she starts with Dancer2.
Hope this will help the beginners.
- Updated some comments in .pm files
- Updated .pod files
  IO came across this while going through the code. Hope this helps.

### CODE REVIEW

**Comment by xsawyerx** [comment]
I want to merge it, but the only problem is that this uses the old tutorial documentation. We would need to apply these settings once we merge the work of @SnigdhaD.

Which reminds me, @SnigdhaD, when can we merge it? :)

**Comment by xsawyerx** [comment]
@SnigdhaD ping?

**Comment by xsawyerx** [comment]
@SnigdhaD ping ping? :)

**Comment by cromedome** [comment]
I am closing this. The current state of documentation doesn't reflect what it was at the time these were submitted, and I can't really include these in any sort of meaningful way as a result.

@sakshee3 thank you for your work on this, and I'm sorry we are unable to merge it. I appreciate you taking the time to contribute this PR!

**Pull request closed without merging**
