### PR TITLE
Move serializer from JSON to JSON::MaybeXS

### PR DESCRIPTION
**Pull request by nunorc**
Tentative pull request to address issue https://github.com/PerlDancer/Dancer2/issues/1196

### CODE REVIEW

**Comment by xsawyerx** [comment]
:+1:

**Comment by veryrusty** [comment]
Looks good! @nunorc++

This also address #900; The only places left using `to_json` are the tests. @nunorc could you modify those to use `encode_json` as well ?

**Comment by cromedome** [comment]
Good work, @nunorc! 

I would like to point out that one test is failing:
```
t/plugin_syntax.t ......................................
    #   Failed test 'plugin_setting returned the expected config'
    #   at t/plugin_syntax.t line 46.
    #          got: '{"plugin":"42"}'
    #     expected: '{"plugin":42}'
    # Looks like you failed 1 test of 5.
t/plugin_syntax.t ...................................... 1/?
#   Failed test 'global and route keywords'
#   at t/plugin_syntax.t line 58.
# Looks like you failed 1 test of 4.
t/plugin_syntax.t ...................................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests
```
If you can fix the test, and take @veryrusty's suggestion, I will get this merged ASAP for you.

Thanks so much!

**Comment by nunorc** [comment]
@cromedome thank you for your comment, the test from `t/plugin_syntax.t` should be passing after commit https://github.com/PerlDancer/Dancer2/pull/1212/commits/10bc227f32c235bd8ad4c6bd91ff0c6e72e98c95 (actually the problem was in the test itself) does it still fails for you?

**Comment by veryrusty** [comment]
@cromedome @nunorc that is a somewhat "tricky" test. The source is loaded from `t/config.yml`. YAML only defines "scalars" and leaves it up to the application for "type" handling. JSON is much more picky about types. Perl is, well, perl. JSON implementations often looks at last context a scalar was used to determine is that 42 should be a string or an integer.  Its messy.

As it stands, its a regression that someone _may_ be relying upon. I haven't had a chance to track down what's going on. We may want to update one of the routes involved to ensure we explicitly numify that 42.

**Comment by nunorc** [comment]
@veryrusty commit https://github.com/PerlDancer/Dancer2/pull/1212/commits/7486abbd869c876696cee5b9b8e24ba30778b53d should address issue https://github.com/PerlDancer/Dancer2/issues/900, all the `to_json` calls to `JSON::MaybeXS` where updated to use `encode` or `encode_json`.

**Comment by nunorc** [comment]
@veryrusty @cromedome yes, I agree that the test in `t/plugin_syntax.t` is tricky, the configuration is loaded using `Config::Any` that uses `YAML::XS` or `YAML::Syck` to actually read the YAML file, and even these two modules have different behaviours. Given that later in the stack, Perl with probably deal ok with either way 42 (or any other config value) is stored as a string or an int, I think we should improve the test itself. Commit https://github.com/PerlDancer/Dancer2/pull/1212/commits/6217ac212f7260145046890e8c3b6df3548e209f uses a _normalize_ function to standardize _number_ values. This makes sure that if the configuration was read correctly (whatever YAML parser was used) the test succeeds. Comments are welcome.

**Comment by cromedome** [comment]
Merged. Closes #900 and #1196. Thanks so much!

**Pull request closed without merging**
